"""Initial tables

Revision ID: 8b4804756b91
Revises: 
Create Date: 2026-08-01 11:45:49.444975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4804756b91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supported_concepts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('canonical_query', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('required_facts', sa.JSON(), nullable=False),
    sa.Column('allowed_visual_types', sa.JSON(), nullable=False),
    sa.Column('template_path', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supported_concepts_code'), 'supported_concepts', ['code'], unique=True)
    op.create_table('video_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('normalized_query', sa.String(), nullable=True),
    sa.Column('concept_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', name='jobstatus'), nullable=False),
    sa.Column('current_stage', sa.Enum('resolving_concept', 'planning_lesson', 'validating_lesson', 'generating_audio', 'generating_visuals', 'rendering_video', 'validating_video', name='jobstage'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('used_fallback', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['supported_concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.Enum('lesson_plan', 'scene_audio', 'scene_visual', 'subtitle', 'thumbnail', 'final_video', name='artifacttype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ready', 'invalid', name='artifactstatus'), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['video_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('stage', sa.Enum('resolving_concept', 'planning_lesson', 'validating_lesson', 'generating_audio', 'generating_visuals', 'rendering_video', 'validating_video', name='jobstage'), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['video_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('estimated_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['video_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('lesson_scenes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('scene_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('narration', sa.String(), nullable=False),
    sa.Column('on_screen_text', sa.JSON(), nullable=True),
    sa.Column('visual_type', sa.String(), nullable=False),
    sa.Column('visual_data', sa.JSON(), nullable=True),
    sa.Column('planned_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('actual_duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['video_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_scenes')
    op.drop_table('lesson_plans')
    op.drop_table('job_events')
    op.drop_table('artifacts')
    op.drop_table('video_jobs')
    op.drop_index(op.f('ix_supported_concepts_code'), table_name='supported_concepts')
    op.drop_table('supported_concepts')
    # ### end Alembic commands ###
